from numpy import cos, sin, sqrt, pi, exp
import sys 
sys.path.append('src')
from src.theoric_channels import *
a = TheoricMaps()

lamb = 0.01
x1 = np.linspace(0,1,1000)
x2 = np.linspace(0.01,400,1000)
xa = np.array([a.non_markov_t_Ana(lamb,i) for i in x2])
xb = np.array([a.non_markov_t_Bellomo(lamb,i) for i in x2])

print('x1 = ', x1)
print('x2 = ', x2)
print('xa = ', xa)
print('xb = ', xb)

#a.plot_storaged('adg',True)
th = np.pi/2
ph = 0
yad = a.ad(x1,th,ph)
ypd = a.pd(x1,th,ph)
yadg = a.adg(x1,th,ph)
ybf = a.b1(x1,th,np.pi/2)
ypf = a.pf(x1,th,ph)
ybpf = a.bpf(x1,th, np.pi/2)
yd = a.d(x1,th,ph)
yl = a.l(x1, th, ph)
yh = a.hw(x1, th, ph)

a.plot_coh('yad', x1, yad, label='yad n-Markov',theta=th,phi=ph)
plt.show()
a.plot_coh('ypd', x1, ypd, label='ypd n-Markov',theta=th,phi=ph)
plt.show()
a.plot_coh('yadg', x1, yadg, label='yadg n-Markov',theta=th,phi=ph)
plt.show()
# a.plot_coh('ybf'1 x1, ybf, label='ybf n-Markov',theta=th,phi=pi/2)
a.plot_coh('ypf', x1, ypf, label='ypf n-Markov',theta=th,phi=ph)
plt.show()
a.plot_coh('ybpf', x1, ybpf, label='ybpf n-Markov',theta=th,phi=pi/2)
plt.show()
a.plot_coh('yd', x1, yd, label='yd n-Markov',theta=th,phi=ph)
plt.show()
a.plot_coh('yl', x1, yl, label='yl n-Markov',theta=th,phi=ph)
plt.show()
a.plot_coh('yh', x1, yh, label='yh n-Markov',theta=th,phi=ph)
plt.show()
sys.exit()
a.plot_theoric(xa,'ad',theta=pi/2,phi=0,descript='isometria_A')
a.plot_theoric(xb,'ad',theta=pi/2,phi=0,descript='isometria_B')
plt.show()
# a.plot_coh('ad', xa, ya, label='Markovianity_A',theta=th,phi=ph) #2
# a.plot_coh('ad', xb, yb, label='Markovianity_B',theta=th,phi=ph) #2
#sys.exit()
# a.plot_theoric(x1,'bpf',theta=pi/2,phi=0,descript='isometria_A')
a.plot_theoric(xa,'ad',theta=pi/2,phi=0,descript='isometria_A')
# plt.xscale('log')

#plt.show()
a.plot_theoric(xb,'ad',theta=pi/2,phi=0,descript='isometria_B')
plt.show()
#a.plot_theoric(x1,'bpf',theta=pi/2,phi=0,descript='isometria_B')
#plt.legend(loc=1)
# plt.xscale('log')

plt.show()
sys.exit()
# a.plot_storaged('ad',True)
a.plot_theoric(xa,'ad',theta=pi/2,phi=0,descript='isometria_A')
a.plot_theoric(xb,'ad',theta=pi/2,phi=0,descript='isometria_B')
plt.legend(loc=1)
plt.show()

# a.plot_storaged('pf',True)
a.plot_theoric(xa,'pf',theta=pi/2,phi=0,descript='isometria_A')
a.plot_theoric(xb,'pf',theta=pi/2,phi=0,descript='isometria_B')
plt.legend(loc=1)
plt.show()

#a.plot_storaged('pd',True)
a.plot_theoric(xa,'pd',theta=pi/2,phi=0,descript='isometria_A')
a.plot_theoric(xb,'pd',theta=pi/2,phi=0,descript='isometria_B')
plt.legend(loc=1)
plt.show()

# a.plot_storaged('bf',True)
a.plot_theoric(xa,'bf',theta=pi/2,phi=pi/2,descript='isometria_A')
a.plot_theoric(xb,'bf',theta=pi/2,phi=pi/2,descript='isometria_B')
plt.legend(loc=1)
plt.show()

# a.plot_storaged('bpf',True)
a.plot_theoric(xa,'bpf',theta=pi/2,phi=0.0,descript='isometria_A')
a.plot_theoric(xb,'bpf',theta=pi/2,phi=0.0,descript='isometria_B')
plt.legend(loc=1)
plt.show()
#s.exit()
# a.plot_storaged('d',True)
a.plot_theoric(xa,'d',theta=pi/2,phi=0,descript='isometria_A')
a.plot_theoric(xb,'d',theta=pi/2,phi=0,descript='isometria_B')
plt.legend(loc=1)
plt.show()
# a.plot_storaged('l',True)
a.plot_theoric(xa,'l',theta=pi/2,phi=0,descript='isometria_A')
a.plot_theoric(xb,'l',theta=pi/2,phi=0,descript='isometria_B')
plt.legend(loc=1)
plt.show()
# a.plot_storaged('adg',True)
a.plot_theoric(xa,'adg',theta=pi/2,phi=0,descript='isometria_A')
a.plot_theoric(xb,'adg',theta=pi/2,phi=0,descript='isometria_B')
plt.legend(loc=1)
plt.show()
# a.plot_storaged('hw',True)
a.plot_theoric(xa,'hw',theta=pi/2,phi=0,descript='isometria_A')
a.plot_theoric(xb,'hw',theta=pi/2,phi=0,descript='isometria_B')
plt.legend(loc=1)
plt.show()
